import { EnquiryForm } from "./EnquiryForm";
import { PortfolioGallery } from "./PortfolioGallery";
import { SiteHeader } from "./SiteHeader";

const services = [
  { image: "/real-grand-opening-room.png", title: "House Warming", text: "Fresh and welcoming decoration for your new beginning." },
  { image: "/cake-story-customised-cake.jpg", title: "Customized Cakes", text: "Beautiful cakes made to match your celebration and preferences." },
  { image: "/real-handcrafted-flower-basket.png", title: "Gifts & Hampers", text: "Personalised gifts and hampers prepared with care." },
  { image: "/real-floral-swag-clean.png", title: "Handmade Decorations", text: "Simple handcrafted details that make your occasion special." },
  { image: "/video-grand-opening-rangoli.png", title: "Wedding Rukhavat", text: "Traditional wedding displays arranged beautifully for your family." },
  { image: "/real-floral-entrance-people-removed.png", title: "Event Decoration", text: "Flower decoration for birthdays, weddings and family celebrations." },
];

const signatureProjects = [
  { image: "/real-floral-entrance-people-removed.png", type: "Office opening", title: "A fresh flower entrance", detail: "Pink and white flowers · Greenery · Pune" },
  { image: "/real-grand-opening-room.png", type: "Opening ceremony", title: "A warm traditional welcome", detail: "Marigold garlands · Flower arrangements · Pune" },
  { image: "/real-pink-white-floral-arrangement.png", type: "Flower arrangement", title: "A pink and white centrepiece", detail: "Fresh flowers · Hand-arranged greenery" },
];

const planningPaths = [
  { number: "01", label: "At home", title: "Make a familiar space feel special.", text: "For house warmings, birthdays, pujas, baby showers and intimate family celebrations.", details: ["Venue-friendly ideas", "Flowers, balloons or handcrafted details", "A plan shaped around your date and budget"], message: "Hello Pune Flower & Event Studio, I would like help planning a home or family celebration." },
  { number: "02", label: "Wedding moments", title: "Celebrate every meaningful detail.", text: "For rukhavat, haldi, engagement, wedding functions and thoughtful gifting moments.", details: ["Traditional and contemporary styling", "Colour and flower direction", "Personal details for your family and venue"], message: "Hello Pune Flower & Event Studio, I would like help planning a wedding-related celebration." },
  { number: "03", label: "Work and occasions", title: "Welcome people beautifully.", text: "For office openings, team celebrations, milestones and corporate welcome spaces.", details: ["Professional, venue-aware setup", "Fresh floral and ceremonial details", "A clear setup plan before the event day"], message: "Hello Pune Flower & Event Studio, I would like help planning an office or corporate event." },
];

const studioPromises = [
  { number: "01", title: "Your people come first", text: "We begin with the feeling you want your family, guests or team to carry home—not with a fixed package." },
  { number: "02", title: "Details with meaning", text: "Flowers, colours, gifts and handcrafted elements are chosen to suit your occasion, traditions and space." },
  { number: "03", title: "A calm celebration day", text: "A clear plan before the event helps the setup feel considered, comfortable and easy to enjoy." },
];

export default function Home() {
  return (
    <main>
      <SiteHeader/>
      <section className="hero" id="top">
        <div className="hero-copy"><p className="eyebrow">Pune floral styling · celebrations with feeling</p><h1>Make the day feel<br/><em>beautifully yours.</em></h1><p className="hero-lead">Flowers, cakes, gifts and thoughtful details for the moments your people will remember—planned around your occasion, space and story.</p><div className="hero-actions"><a className="button" href="https://wa.me/918793368616?text=Hello%2C%20I%20would%20like%20to%20discuss%20decoration%20for%20my%20event." target="_blank" rel="noreferrer">Tell us about your event <span>↗</span></a><a className="text-link" href="#services">See our services <span>↓</span></a></div><div className="hero-note"><span>✦</span><p><strong>Personal, not pre-packaged</strong><br/>A celebration shaped around what matters to you.</p></div></div>
        <div className="hero-visual"><div className="hero-image" role="img" aria-label="Elegant floral event decoration"/><div className="hero-card"><span>Thoughtfully styled</span><strong>For your people</strong><small>Pune &amp; nearby areas</small></div><span className="botanical botanical-one">❧</span><span className="botanical botanical-two">❀</span></div>
      </section>
      <aside className="home-contact-bar" aria-label="Quick contact options">
        <p><span>Need help planning?</span><strong>Speak with us directly</strong></p>
        <div>
          <a href="tel:+918793368616" aria-label="Call Pune Flower and Event Studio"><span className="contact-symbol" aria-hidden="true">☎</span><span><small>Call us</small><strong>+91 87933 68616</strong></span></a>
          <a href="https://wa.me/918793368616?text=Hello%20Pune%20Flower%20%26%20Event%20Studio%2C%20I%20would%20like%20to%20know%20more%20about%20your%20decoration%20services." target="_blank" rel="noreferrer" aria-label="Chat with Pune Flower and Event Studio on WhatsApp"><span className="contact-symbol whatsapp-symbol" aria-hidden="true">◉</span><span><small>WhatsApp</small><strong>Send a message</strong></span></a>
          <a href="#gallery" aria-label="View our real decoration work"><span className="contact-symbol" aria-hidden="true">✿</span><span><small>Real decorations</small><strong>View our work</strong></span></a>
        </div>
      </aside>
      <section className="trust-strip" aria-label="Our service promises"><div><strong>Real celebrations</strong><span>Ideas designed for actual people and venues</span></div><div><strong>Personal styling</strong><span>Flowers, colours and details shaped around you</span></div><div><strong>Pune based</strong><span>Local planning, setup and practical support</span></div><div><strong>Clear guidance</strong><span>A considered plan before the celebration day</span></div></section>
      <section className="signature-showcase" aria-labelledby="signature-heading">
        <div className="signature-heading"><div><p className="eyebrow">Recent decorations</p><h2 id="signature-heading">Real occasions,<br/><em>happy memories.</em></h2></div><p>Have a look at some of the decorations we have created for our customers in Pune.</p></div>
        <div className="signature-projects">{signatureProjects.map((project,index)=><a className="signature-project" href="#gallery" key={project.title}><div className="signature-project-image"><img src={project.image} alt={project.title}/><span>0{index+1}</span></div><p>{project.type}</p><h3>{project.title}</h3><small>{project.detail}</small></a>)}</div>
        <div className="botanical-divider" aria-hidden="true"><span>✦</span></div>
      </section>
      <section className="intro" id="services"><div><p className="eyebrow">Our services</p><h2>Something beautiful<br/>for every occasion.</h2></div><p>Choose the service that feels closest to your celebration. We then shape the flowers, colours and details around your venue, ideas and budget.</p></section>
      <section className="services-grid">{services.map((service,index)=><article className="service-card service-card-visual" key={service.title}><div className="service-image"><img src={service.image} alt=""/><span className="service-number">0{index+1}</span></div><div className="service-card-copy"><h3>{service.title}</h3><p>{service.text}</p><a href="#enquire" aria-label={`Plan ${service.title}`}>Plan this occasion <span>↗</span></a></div></article>)}</section>
      <section className="planning-path" id="plan" aria-labelledby="planning-path-heading"><div className="planning-path-heading"><p className="eyebrow">Start with your occasion</p><h2 id="planning-path-heading">A more personal way<br/><em>to begin planning.</em></h2><p>Not sure which service to choose? Start with the kind of moment you are creating. We will help turn it into a clear, beautiful plan.</p></div><div className="planning-path-grid">{planningPaths.map((path) => <article className="planning-path-card" key={path.label}><span className="planning-number">{path.number}</span><p className="planning-label">{path.label}</p><h3>{path.title}</h3><p>{path.text}</p><ul>{path.details.map((detail) => <li key={detail}>{detail}</li>)}</ul><a className="text-link" href={`https://wa.me/918793368616?text=${encodeURIComponent(path.message)}`} target="_blank" rel="noreferrer">Start this conversation <span>↗</span></a></article>)}</div></section>
      <section className="studio-promise" aria-labelledby="studio-promise-heading">
        <div className="studio-promise-image"><img src="/real-floral-office-desk-person-removed.png" alt="A real floral setting prepared by Pune Flower and Event Studio"/></div>
        <div className="studio-promise-copy"><p className="eyebrow">A celebration should feel like you</p><h2 id="studio-promise-heading">Not just a setup.<br/><em>A feeling in the room.</em></h2><p>Beautiful events are made from the little things people notice: a welcome that feels warm, colours that feel right, and thoughtful details that bring everyone closer.</p><div className="studio-promise-list">{studioPromises.map((promise) => <article key={promise.number}><span>{promise.number}</span><div><h3>{promise.title}</h3><p>{promise.text}</p></div></article>)}</div><a className="text-link" href="#enquire">Plan a meaningful celebration <span>↓</span></a></div>
      </section>
      <section className="story" id="story"><div className="story-image"><span className="story-seal">Made with<br/><strong>heart</strong><br/>in Pune</span></div><div className="story-copy"><p className="eyebrow">About our work</p><h2>Simple, personal<br/><em>and made with care.</em></h2><p>Every celebration is different. We listen to your ideas and create decoration that feels right for your family, occasion and venue.</p><p>Whether it is a new home, wedding, birthday, puja or a small family gathering, we are happy to make it look special.</p><blockquote className="section-quote">“The loveliest celebrations are not remembered for what filled the room, but for the love felt inside it.”</blockquote><div className="signature">Pune Flower &amp; Event Studio</div></div></section>
      <section className="gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">Our real work</p><h2>Decoration made for<br/><em>real celebrations.</em></h2></div><a className="text-link" href="https://wa.me/918793368616" target="_blank" rel="noreferrer">Ask for more photos <span>↗</span></a></div><PortfolioGallery/><p className="gallery-quote">“Long after the flowers are gone, the feeling of being together stays.”</p></section>
      <section className="proof-band" aria-label="Why customers choose us"><p className="eyebrow">Why customers choose us</p><div><article><strong>Real work</strong><span>The photographs on this website are from decorations we have created.</span></article><article><strong>Personal help</strong><span>You can speak directly with us while planning your occasion.</span></article><article><strong>Flexible choices</strong><span>We can adjust the decoration to suit your venue, preferences and budget.</span></article></div><a className="text-link" href="#contact">Talk to us <span>↗</span></a></section>
      <section className="process"><p className="eyebrow">Easy to plan</p><h2>A clear plan, from first message<br/>to celebration day.</h2><div className="process-grid"><div><span>01</span><h3>Share the essentials</h3><p>Tell us your occasion, date, venue, ideas and approximate budget.</p></div><div><span>02</span><h3>Shape the look</h3><p>We discuss suitable flowers, colours, styling and practical venue details.</p></div><div><span>03</span><h3>Confirm your plan</h3><p>Receive a clear proposal before we confirm the decoration and setup requirements.</p></div><div><span>04</span><h3>Enjoy the moment</h3><p>We complete the agreed setup so you can spend time with your guests.</p></div></div></section>
      <section className="planner" id="enquire"><div className="planner-copy"><p className="eyebrow">Send an enquiry</p><h2>Tell us about<br/><em>your occasion.</em></h2><p>Share your date, location and the kind of decoration you need. We will understand your ideas and reply to you on WhatsApp.</p></div><EnquiryForm/></section>
      <section className="faq" id="faq"><div className="faq-heading"><p className="eyebrow">Good to know</p><h2>Questions, answered.</h2><p>If your question is not here, message us and we will be happy to help.</p></div><div className="faq-list"><details><summary>How early should I book my decoration?<span>+</span></summary><p>For smaller celebrations, contact us at least 7–10 days ahead. Weddings, corporate events and detailed custom work are best planned 2–4 weeks in advance.</p></details><details><summary>Can every design be customised?<span>+</span></summary><p>Yes. Colours, flowers, materials and styling are adapted to your occasion, venue and budget. Reference photographs are welcome as inspiration.</p></details><details><summary>Which areas do you serve?<span>+</span></summary><p>We primarily serve Pune and nearby areas. Share your venue location during enquiry and we will confirm availability and any travel requirements.</p></details><details><summary>How is pricing decided?<span>+</span></summary><p>Pricing depends on the scale, flowers, materials, venue, setup time and custom elements. We provide a clear estimate after understanding your requirements.</p></details><details><summary>Do you also provide cakes, gifts and hampers?<span>+</span></summary><p>Yes. Customised cakes, thoughtful gifts, hampers and handcrafted details can be planned alongside your decoration.</p></details></div></section>
      <section className="contact" id="contact"><div><p className="eyebrow">We are happy to help</p><h2>Planning a special<br/>occasion?</h2><p>Call or message us with your date, location and requirement. We will guide you through the available options.</p></div><div className="contact-actions"><a className="button button-light" href="https://wa.me/918793368616?text=Hello%20Pune%20Flower%20%26%20Event%20Studio%2C%20I%20have%20an%20event%20enquiry." target="_blank" rel="noreferrer">Message on WhatsApp <span>↗</span></a><a className="phone" href="tel:+918793368616"><small>Call for bookings &amp; enquiries</small><strong>+91 87933 68616</strong></a></div></section>
      <footer><a className="brand brand-footer" href="/" aria-label="Return to homepage"><img className="brand-logo" src="/pune-flower-logo-mark.svg" alt=""/><span><strong>Pune</strong><small>Flower &amp; Event Studio</small></span></a><p>We decorate moments you cherish forever.</p><div><a href="#services">Services</a><a href="#gallery">Our work</a><a href="#contact">Contact</a></div><div className="footer-legal"><a href="/privacy-policy">Privacy</a><a href="/terms">Terms</a><a href="/booking-policy">Booking policy</a></div><small>© 2026 Pune Flower &amp; Event Studio. All rights reserved.</small></footer>
      <a className="mobile-whatsapp" href="#enquire" aria-label="Start an event enquiry">Enquire now <span>↗</span></a>
    </main>
  );
}
