import { EnquiryForm } from "./EnquiryForm";
import { PortfolioGallery } from "./PortfolioGallery";
import { SiteHeader } from "./SiteHeader";

const services = [
  { image: "/real-grand-opening-room.png", title: "House Warming", text: "Warm, graceful décor for a beautiful new beginning." },
  { image: "/cake-story-customised-cake.jpg", title: "Customized Cakes", text: "Elegant celebration cakes thoughtfully designed around your story." },
  { image: "/real-handcrafted-flower-basket.png", title: "Gifts & Hampers", text: "Thoughtful, personalised keepsakes made for the moment." },
  { image: "/real-floral-swag-clean.png", title: "Crafted Details", text: "Delicate handmade elements that make every setting yours." },
  { image: "/video-grand-opening-rangoli.png", title: "Wedding Rukhavat", text: "Elegant traditional displays with a contemporary finish." },
  { image: "/real-floral-entrance-people-removed.png", title: "Event Décor", text: "Complete styling for weddings, milestones and intimate events." },
];

const signatureProjects = [
  { image: "/real-floral-entrance-people-removed.png", type: "Corporate celebration", title: "A botanical grand entrance", detail: "Fresh rose arch · Marigold accents · Pune" },
  { image: "/real-grand-opening-room.png", type: "Opening ceremony", title: "A warm ceremonial welcome", detail: "Marigold garlands · Floral styling · Pune" },
  { image: "/real-pink-white-floral-arrangement.png", type: "Floral artistry", title: "Blush garden centrepiece", detail: "Fresh blooms · Hand-layered greenery · Bespoke" },
];

export default function Home() {
  return (
    <main>
      <SiteHeader/>
      <section className="hero" id="top">
        <div className="hero-copy"><p className="eyebrow">Flowers · Emotions · Elegance</p><h1>We decorate moments<br/><em>you cherish forever.</em></h1><p className="hero-lead">Thoughtful flowers, handcrafted details and elegant event styling—created in Pune for celebrations that feel entirely your own.</p><div className="hero-actions"><a className="button" href="https://wa.me/918793368616?text=Hello%2C%20I%20would%20like%20to%20discuss%20decoration%20for%20my%20event." target="_blank" rel="noreferrer">Start your celebration <span>↗</span></a><a className="text-link" href="#services">Explore our services <span>↓</span></a></div><div className="hero-note"><span>✦</span><p><strong>Made for your story</strong><br/>Every detail is personalised with care.</p></div></div>
        <div className="hero-visual"><div className="hero-image" role="img" aria-label="Elegant floral event decoration"/><div className="hero-card"><span>Now accepting</span><strong>Celebration bookings</strong><small>Pune &amp; nearby areas</small></div><span className="botanical botanical-one">❧</span><span className="botanical botanical-two">❀</span></div>
      </section>
      <section className="trust-strip" aria-label="Our service promises"><div><strong>Fresh & thoughtful</strong><span>Flowers and details chosen with care</span></div><div><strong>Made for you</strong><span>Every concept is personalised</span></div><div><strong>Pune based</strong><span>Local planning and dependable setup</span></div><div><strong>Personally handled</strong><span>One team from enquiry to celebration</span></div></section>
      <section className="signature-showcase" aria-labelledby="signature-heading">
        <div className="signature-heading"><div><p className="eyebrow">Signature celebrations</p><h2 id="signature-heading">Real occasions,<br/><em>beautifully remembered.</em></h2></div><p>Explore a few settings created with fresh flowers, handcrafted detail and a deep respect for the occasion.</p></div>
        <div className="signature-projects">{signatureProjects.map((project,index)=><a className="signature-project" href="#gallery" key={project.title}><div className="signature-project-image"><img src={project.image} alt={project.title}/><span>0{index+1}</span></div><p>{project.type}</p><h3>{project.title}</h3><small>{project.detail}</small></a>)}</div>
        <div className="botanical-divider" aria-hidden="true"><span>✦</span></div>
      </section>
      <section className="intro" id="services"><div><p className="eyebrow">Our services</p><h2>Everything your moment<br/>deserves.</h2></div><p>From the first flower to the final finishing touch, we bring every element together with warmth, artistry and attention to detail.</p></section>
      <section className="services-grid">{services.map((service,index)=><article className="service-card service-card-visual" key={service.title}><div className="service-image"><img src={service.image} alt=""/><span className="service-number">0{index+1}</span></div><div className="service-card-copy"><h3>{service.title}</h3><p>{service.text}</p><a href="#enquire" aria-label={`Plan ${service.title}`}>Plan this occasion <span>↗</span></a></div></article>)}</section>
      <section className="story" id="story"><div className="story-image"><span className="story-seal">Made with<br/><strong>heart</strong><br/>in Pune</span></div><div className="story-copy"><p className="eyebrow">Our approach</p><h2>Beautifully personal,<br/><em>effortlessly elegant.</em></h2><p>We believe the most memorable celebrations are the ones that feel like you. That is why every colour, flower and handcrafted detail begins with your story.</p><p>Whether it is a new home, a wedding ritual or a joyful birthday, we create settings that feel warm, refined and full of meaning.</p><div className="signature">Pune Flower &amp; Event Studio</div></div></section>
      <section className="gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">A glimpse of our work</p><h2>Details that become<br/><em>lasting memories.</em></h2></div><a className="text-link" href="https://wa.me/918793368616" target="_blank" rel="noreferrer">Request our portfolio <span>↗</span></a></div><PortfolioGallery/></section>
      <section className="proof-band" aria-label="Why clients choose the studio"><p className="eyebrow">The confidence of real work</p><div><article><strong>Authentic portfolio</strong><span>Every photograph shown here comes from real decoration work.</span></article><article><strong>One personal team</strong><span>Your enquiry, concept and setup are handled with continuity and care.</span></article><article><strong>Designed around you</strong><span>Colours, flowers and details are adapted to your venue and occasion.</span></article></div><a className="text-link" href="#contact">Speak with the studio <span>↗</span></a></section>
      <section className="process"><p className="eyebrow">Simple, thoughtful, seamless</p><h2>Your celebration, in three steps.</h2><div className="process-grid"><div><span>01</span><h3>Share your vision</h3><p>Tell us your occasion, date, venue and the feeling you would love to create.</p></div><div><span>02</span><h3>We design the details</h3><p>We shape a personalised concept, palette and plan around your preferences.</p></div><div><span>03</span><h3>Cherish the moment</h3><p>We bring it all together beautifully, so you can simply enjoy your celebration.</p></div></div></section>
      <section className="planner" id="enquire"><div className="planner-copy"><p className="eyebrow">Plan your celebration</p><h2>Tell us what you<br/><em>have in mind.</em></h2><p>A few simple details help us understand your occasion before we speak. Your enquiry will open in WhatsApp, ready to send.</p><div className="planner-tip"><span>i</span><p><strong>Helpful to know</strong><br/>For larger events, contacting us 2–4 weeks ahead gives us the best choice of flowers and materials.</p></div></div><EnquiryForm/></section>
      <section className="faq" id="faq"><div className="faq-heading"><p className="eyebrow">Good to know</p><h2>Questions, answered.</h2><p>If your question is not here, message us and we will be happy to help.</p></div><div className="faq-list"><details><summary>How early should I book my decoration?<span>+</span></summary><p>For smaller celebrations, contact us at least 7–10 days ahead. Weddings, corporate events and detailed custom work are best planned 2–4 weeks in advance.</p></details><details><summary>Can every design be customised?<span>+</span></summary><p>Yes. Colours, flowers, materials and styling are adapted to your occasion, venue and budget. Reference photographs are welcome as inspiration.</p></details><details><summary>Which areas do you serve?<span>+</span></summary><p>We primarily serve Pune and nearby areas. Share your venue location during enquiry and we will confirm availability and any travel requirements.</p></details><details><summary>How is pricing decided?<span>+</span></summary><p>Pricing depends on the scale, flowers, materials, venue, setup time and custom elements. We provide a clear estimate after understanding your requirements.</p></details><details><summary>Do you also provide cakes, gifts and hampers?<span>+</span></summary><p>Yes. Customised cakes, thoughtful gifts, hampers and handcrafted details can be planned alongside your decoration.</p></details></div></section>
      <section className="contact" id="contact"><div><p className="eyebrow">Let’s create something beautiful</p><h2>Have a celebration<br/>in mind?</h2><p>Tell us a little about your date and occasion. We will help you turn it into a setting worth remembering.</p></div><div className="contact-actions"><a className="button button-light" href="https://wa.me/918793368616?text=Hello%20Pune%20Flower%20%26%20Event%20Studio%2C%20I%20have%20an%20event%20enquiry." target="_blank" rel="noreferrer">Enquire on WhatsApp <span>↗</span></a><a className="phone" href="tel:+918793368616"><small>Call for bookings &amp; enquiries</small><strong>+91 87933 68616</strong></a></div></section>
      <footer><a className="brand brand-footer" href="/" aria-label="Return to homepage"><img className="brand-logo" src="/pune-flower-logo-mark.svg" alt=""/><span><strong>Pune</strong><small>Flower &amp; Event Studio</small></span></a><p>We decorate moments you cherish forever.</p><div><a href="#services">Services</a><a href="#gallery">Our work</a><a href="#contact">Contact</a></div><div className="footer-legal"><a href="/privacy-policy">Privacy</a><a href="/terms">Terms</a><a href="/booking-policy">Booking policy</a></div><small>© 2026 Pune Flower &amp; Event Studio. All rights reserved.</small></footer>
      <a className="mobile-whatsapp" href="#enquire" aria-label="Start an event enquiry">Plan an event <span>↗</span></a>
    </main>
  );
}
