import { EnquiryForm } from "./EnquiryForm";
import { PortfolioGallery } from "./PortfolioGallery";
import { SiteHeader } from "./SiteHeader";

const services = [
  { image: "/real-grand-opening-room.png", title: "House Warming", text: "Fresh and welcoming decoration for your new beginning." },
  { image: "/cake-story-customised-cake.jpg", title: "Customized Cakes", text: "Beautiful cakes made to match your celebration and preferences." },
  { image: "/real-handcrafted-flower-basket.png", title: "Gifts & Hampers", text: "Personalised gifts and hampers prepared with care." },
  { image: "/real-floral-swag-clean.png", title: "Handmade Decorations", text: "Simple handcrafted details that make your occasion special." },
  { image: "/video-grand-opening-rangoli.png", title: "Wedding Rukhavat", text: "Traditional wedding displays arranged beautifully for your family." },
  { image: "/real-floral-entrance-people-removed.png", title: "Event Decoration", text: "Flower decoration for birthdays, weddings and family celebrations." },
];

const signatureProjects = [
  { image: "/real-floral-entrance-people-removed.png", type: "Office opening", title: "A fresh flower entrance", detail: "Pink and white flowers · Greenery · Pune" },
  { image: "/real-grand-opening-room.png", type: "Opening ceremony", title: "A warm traditional welcome", detail: "Marigold garlands · Flower arrangements · Pune" },
  { image: "/real-pink-white-floral-arrangement.png", type: "Flower arrangement", title: "A pink and white centrepiece", detail: "Fresh flowers · Hand-arranged greenery" },
];

export default function Home() {
  return (
    <main>
      <SiteHeader/>
      <section className="hero" id="top">
        <div className="hero-copy"><p className="eyebrow">Flowers · Celebrations · Happiness</p><h1>We decorate moments<br/><em>you cherish forever.</em></h1><p className="hero-lead">Beautiful flower decoration, cakes, gifts and handmade details for your special occasions in Pune.</p><div className="hero-actions"><a className="button" href="https://wa.me/918793368616?text=Hello%2C%20I%20would%20like%20to%20discuss%20decoration%20for%20my%20event." target="_blank" rel="noreferrer">Tell us about your event <span>↗</span></a><a className="text-link" href="#services">See our services <span>↓</span></a></div><div className="hero-note"><span>✦</span><p><strong>Made for every celebration</strong><br/>Simple and beautiful options for different budgets.</p></div></div>
        <div className="hero-visual"><div className="hero-image" role="img" aria-label="Elegant floral event decoration"/><div className="hero-card"><span>Now accepting</span><strong>Celebration bookings</strong><small>Pune &amp; nearby areas</small></div><span className="botanical botanical-one">❧</span><span className="botanical botanical-two">❀</span></div>
      </section>
      <aside className="home-contact-bar" aria-label="Quick contact options">
        <p><span>Need help planning?</span><strong>Speak with us directly</strong></p>
        <div>
          <a href="tel:+918793368616" aria-label="Call Pune Flower and Event Studio"><span className="contact-symbol" aria-hidden="true">☎</span><span><small>Call us</small><strong>+91 87933 68616</strong></span></a>
          <a href="https://wa.me/918793368616?text=Hello%20Pune%20Flower%20%26%20Event%20Studio%2C%20I%20would%20like%20to%20know%20more%20about%20your%20decoration%20services." target="_blank" rel="noreferrer" aria-label="Chat with Pune Flower and Event Studio on WhatsApp"><span className="contact-symbol whatsapp-symbol" aria-hidden="true">◉</span><span><small>WhatsApp</small><strong>Send a message</strong></span></a>
          <a href="#gallery" aria-label="View our real decoration work"><span className="contact-symbol" aria-hidden="true">✿</span><span><small>Real decorations</small><strong>View our work</strong></span></a>
        </div>
      </aside>
      <section className="trust-strip" aria-label="Our service promises"><div><strong>Fresh flowers</strong><span>Chosen carefully for your occasion</span></div><div><strong>Your choice</strong><span>Colours and details can be changed</span></div><div><strong>Pune based</strong><span>Easy local planning and setup</span></div><div><strong>Friendly service</strong><span>We help you from enquiry to celebration</span></div></section>
      <section className="signature-showcase" aria-labelledby="signature-heading">
        <div className="signature-heading"><div><p className="eyebrow">Recent decorations</p><h2 id="signature-heading">Real occasions,<br/><em>happy memories.</em></h2></div><p>Have a look at some of the decorations we have created for our customers in Pune.</p></div>
        <div className="signature-projects">{signatureProjects.map((project,index)=><a className="signature-project" href="#gallery" key={project.title}><div className="signature-project-image"><img src={project.image} alt={project.title}/><span>0{index+1}</span></div><p>{project.type}</p><h3>{project.title}</h3><small>{project.detail}</small></a>)}</div>
        <div className="botanical-divider" aria-hidden="true"><span>✦</span></div>
      </section>
      <section className="intro" id="services"><div><p className="eyebrow">Our services</p><h2>Something beautiful<br/>for every occasion.</h2></div><p>Choose the service you need and share your ideas with us. We can adjust the colours, flowers and details to suit your event and budget.</p></section>
      <section className="services-grid">{services.map((service,index)=><article className="service-card service-card-visual" key={service.title}><div className="service-image"><img src={service.image} alt=""/><span className="service-number">0{index+1}</span></div><div className="service-card-copy"><h3>{service.title}</h3><p>{service.text}</p><a href="#enquire" aria-label={`Plan ${service.title}`}>Plan this occasion <span>↗</span></a></div></article>)}</section>
      <section className="story" id="story"><div className="story-image"><span className="story-seal">Made with<br/><strong>heart</strong><br/>in Pune</span></div><div className="story-copy"><p className="eyebrow">About our work</p><h2>Simple, personal<br/><em>and made with care.</em></h2><p>Every celebration is different. We listen to your ideas and create decoration that feels right for your family, occasion and venue.</p><p>Whether it is a new home, wedding, birthday, puja or a small family gathering, we are happy to make it look special.</p><blockquote className="section-quote">“Flowers do not simply decorate a moment; they help it bloom.”</blockquote><div className="signature">Pune Flower &amp; Event Studio</div></div></section>
      <section className="gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">Our real work</p><h2>Decoration made for<br/><em>real celebrations.</em></h2></div><a className="text-link" href="https://wa.me/918793368616" target="_blank" rel="noreferrer">Ask for more photos <span>↗</span></a></div><PortfolioGallery/><p className="gallery-quote">“Made with flowers, held in memory, cherished in the heart.”</p></section>
      <section className="proof-band" aria-label="Why customers choose us"><p className="eyebrow">Why customers choose us</p><div><article><strong>Real work</strong><span>The photographs on this website are from decorations we have created.</span></article><article><strong>Personal help</strong><span>You can speak directly with us while planning your occasion.</span></article><article><strong>Flexible choices</strong><span>We can adjust the decoration to suit your venue, preferences and budget.</span></article></div><a className="text-link" href="#contact">Talk to us <span>↗</span></a></section>
      <section className="process"><p className="eyebrow">Easy to plan</p><h2>Your decoration, in three simple steps.</h2><div className="process-grid"><div><span>01</span><h3>Tell us the details</h3><p>Share your occasion, date, venue, ideas and approximate budget.</p></div><div><span>02</span><h3>Choose what suits you</h3><p>We suggest suitable flowers, colours and decoration options.</p></div><div><span>03</span><h3>Enjoy your celebration</h3><p>We complete the setup so you can spend time with your guests.</p></div></div></section>
      <section className="planner" id="enquire"><div className="planner-copy"><p className="eyebrow">Send an enquiry</p><h2>Tell us about<br/><em>your occasion.</em></h2><p>Share a few details and we will suggest suitable decoration options. Your enquiry will open in WhatsApp, ready to send.</p><div className="planner-tip"><span>i</span><p><strong>Options for different budgets</strong><br/>Tell us your approximate budget and priorities. We will suggest what can work beautifully within it.</p></div></div><EnquiryForm/></section>
      <section className="faq" id="faq"><div className="faq-heading"><p className="eyebrow">Good to know</p><h2>Questions, answered.</h2><p>If your question is not here, message us and we will be happy to help.</p></div><div className="faq-list"><details><summary>How early should I book my decoration?<span>+</span></summary><p>For smaller celebrations, contact us at least 7–10 days ahead. Weddings, corporate events and detailed custom work are best planned 2–4 weeks in advance.</p></details><details><summary>Can every design be customised?<span>+</span></summary><p>Yes. Colours, flowers, materials and styling are adapted to your occasion, venue and budget. Reference photographs are welcome as inspiration.</p></details><details><summary>Which areas do you serve?<span>+</span></summary><p>We primarily serve Pune and nearby areas. Share your venue location during enquiry and we will confirm availability and any travel requirements.</p></details><details><summary>How is pricing decided?<span>+</span></summary><p>Pricing depends on the scale, flowers, materials, venue, setup time and custom elements. We provide a clear estimate after understanding your requirements.</p></details><details><summary>Do you also provide cakes, gifts and hampers?<span>+</span></summary><p>Yes. Customised cakes, thoughtful gifts, hampers and handcrafted details can be planned alongside your decoration.</p></details></div></section>
      <section className="contact" id="contact"><div><p className="eyebrow">We are happy to help</p><h2>Planning a special<br/>occasion?</h2><p>Call or message us with your date, location and requirement. We will guide you through the available options.</p></div><div className="contact-actions"><a className="button button-light" href="https://wa.me/918793368616?text=Hello%20Pune%20Flower%20%26%20Event%20Studio%2C%20I%20have%20an%20event%20enquiry." target="_blank" rel="noreferrer">Message on WhatsApp <span>↗</span></a><a className="phone" href="tel:+918793368616"><small>Call for bookings &amp; enquiries</small><strong>+91 87933 68616</strong></a></div></section>
      <footer><a className="brand brand-footer" href="/" aria-label="Return to homepage"><img className="brand-logo" src="/pune-flower-logo-mark.svg" alt=""/><span><strong>Pune</strong><small>Flower &amp; Event Studio</small></span></a><p>We decorate moments you cherish forever.</p><div><a href="#services">Services</a><a href="#gallery">Our work</a><a href="#contact">Contact</a></div><div className="footer-legal"><a href="/privacy-policy">Privacy</a><a href="/terms">Terms</a><a href="/booking-policy">Booking policy</a></div><small>© 2026 Pune Flower &amp; Event Studio. All rights reserved.</small></footer>
      <a className="mobile-whatsapp" href="#enquire" aria-label="Start an event enquiry">Enquire now <span>↗</span></a>
    </main>
  );
}
